#!/bin/bash

# Script to download real animal sounds from Freesound.org or similar free sources
# Note: This requires manual setup with API keys or using public domain sources

echo "Animal Sound Download Helper"
echo "============================"
echo ""
echo "To get real animal sounds, you have several options:"
echo ""
echo "1. FREESOUND.ORG (Recommended - Free with attribution)"
echo "   - Visit: https://freesound.org"
echo "   - Search for each animal name + 'sound' or 'call'"
echo "   - Download 5-second clips (or trim to 5 seconds)"
echo "   - Save to: public/sounds/[animal].wav"
echo ""
echo "2. ZAPSPLAT.COM (Free with attribution)"
echo "   - Visit: https://www.zapsplat.com/sound-effect-categories/"
echo "   - Browse animal sounds category"
echo "   - Download and save to public/sounds/"
echo ""
echo "3. BBC SOUND EFFECTS (Public Domain)"
echo "   - Visit: https://sound-effects.bbcrewind.co.uk/"
echo "   - Search for animal names"
echo "   - Download WAV files"
echo ""
echo "4. YOUTUBE AUDIO LIBRARY (Free)"
echo "   - Search YouTube for '[animal] sound effect'"
echo "   - Use youtube-dl or online converter"
echo ""
echo "Animals needed (50 total):"
echo "lion, elephant, dog, cat, cow, horse, sheep, pig, chicken, duck,"
echo "goose, turkey, rooster, frog, owl, crow, parrot, peacock, monkey, bear,"
echo "wolf, fox, deer, goat, donkey, zebra, giraffe, hippo, rhino, tiger,"
echo "leopard, cheetah, panda, koala, kangaroo, penguin, seal, dolphin, whale, snake,"
echo "crocodile, bee, cricket, mosquito, seagull, eagle, hawk, coyote, hyena, gorilla"
echo ""
echo "IMPORTANT: Make sure each file is:"
echo "  - Exactly 5 seconds long (trim if needed)"
echo "  - Named correctly: [animal].wav"
echo "  - Saved in: public/sounds/"
echo ""
echo "To trim audio to 5 seconds using ffmpeg:"
echo "  ffmpeg -i input.wav -t 5 -acodec copy output.wav"
