// Animal action sentences for the soundboard
export const sentences = [
    { id: 1, key: 'voglio_cioccolato', name: 'Io voglio il cioccolato', image: '/sentences/voglio_cioccolato.svg', sound: '/sounds/voglio_cioccolato.wav' },
    { id: 2, key: 'ho_fame', name: 'Ho fame', image: '/sentences/ho_fame.svg', sound: '/sounds/ho_fame.wav' },
    { id: 3, key: 'andiamo_casa', name: 'Andiamo a casa', image: '/sentences/andiamo_casa.svg', sound: '/sounds/andiamo_casa.wav' },
    { id: 4, key: 'andiamo_scuola', name: 'Andiamo a scuola', image: '/sentences/andiamo_scuola.svg', sound: '/sounds/andiamo_scuola.wav' },
    { id: 5, key: 'ho_sete', name: 'Ho sete', image: '/sentences/ho_sete.svg', sound: '/sounds/ho_sete.wav' },
    { id: 6, key: 'buona_pappa', name: 'Che buona questa pappa', image: '/sentences/buona_pappa.svg', sound: '/sounds/buona_pappa.wav' },
    { id: 7, key: 'andiamo_tata', name: 'Andiamo dalla tata', image: '/sentences/andiamo_tata.svg', sound: '/sounds/andiamo_tata.wav' },
    { id: 8, key: 'voglio_passeggiata', name: 'Voglio fare una passeggiata', image: '/sentences/voglio_passeggiata.svg', sound: '/sounds/voglio_passeggiata.wav' },
    { id: 9, key: 'leone_ruggisce', name: 'Il leone ruggisce', image: '/sentences/leone_ruggisce.svg', sound: '/sounds/leone_ruggisce.wav' },
    { id: 10, key: 'elefante_strombetta', name: 'L\'elefante strombetta', image: '/sentences/elefante_strombetta.svg', sound: '/sounds/elefante_strombetta.wav' },
    { id: 11, key: 'cane_abbaia', name: 'Il cane abbaia', image: '/sentences/cane_abbaia.svg', sound: '/sounds/cane_abbaia.wav' },
    { id: 12, key: 'gatto_miagola', name: 'Il gatto miagola', image: '/sentences/gatto_miagola.svg', sound: '/sounds/gatto_miagola.wav' },
    { id: 13, key: 'mucca_muggisce', name: 'La mucca muggisce', image: '/sentences/mucca_muggisce.svg', sound: '/sounds/mucca_muggisce.wav' },
    { id: 14, key: 'cavallo_nitrisce', name: 'Il cavallo nitrisce', image: '/sentences/cavallo_nitrisce.svg', sound: '/sounds/cavallo_nitrisce.wav' },
    { id: 15, key: 'pecora_bela', name: 'La pecora bela', image: '/sentences/pecora_bela.svg', sound: '/sounds/pecora_bela.wav' },
    { id: 16, key: 'maiale_grugnisce', name: 'Il maiale grugnisce', image: '/sentences/maiale_grugnisce.svg', sound: '/sounds/maiale_grugnisce.wav' },
    { id: 17, key: 'gallina_cluck', name: 'La gallina fa cluck', image: '/sentences/gallina_cluck.svg', sound: '/sounds/gallina_cluck.wav' },
    { id: 18, key: 'anatra_quack', name: 'L\'anatra fa quack', image: '/sentences/anatra_quack.svg', sound: '/sounds/anatra_quack.wav' },
    { id: 19, key: 'tacchino_gobble', name: 'Il tacchino fa gobble', image: '/sentences/tacchino_gobble.svg', sound: '/sounds/tacchino_gobble.wav' },
    { id: 20, key: 'gallo_chicchirichi', name: 'Il gallo fa chicchirichì', image: '/sentences/gallo_chicchirichi.svg', sound: '/sounds/gallo_chicchirichi.wav' },
    { id: 21, key: 'rana_gracida', name: 'La rana gracida', image: '/sentences/rana_gracida.svg', sound: '/sounds/rana_gracida.wav' },
    { id: 22, key: 'gufo_chiu', name: 'Il gufo fa chiu', image: '/sentences/gufo_chiu.svg', sound: '/sounds/gufo_chiu.wav' },
    { id: 23, key: 'corvo_gracchia', name: 'Il corvo gracchia', image: '/sentences/corvo_gracchia.svg', sound: '/sounds/corvo_gracchia.wav' },
    { id: 24, key: 'pappagallo_parla', name: 'Il pappagallo parla', image: '/sentences/pappagallo_parla.svg', sound: '/sounds/pappagallo_parla.wav' },
    { id: 25, key: 'pavone_urla', name: 'Il pavone urlò', image: '/sentences/pavone_urla.svg', sound: '/sounds/pavone_urla.wav' },
    { id: 26, key: 'scimmia_urla', name: 'La scimmia urlò', image: '/sentences/scimmia_urla.svg', sound: '/sounds/scimmia_urla.wav' },
    { id: 27, key: 'orso_ruggisce', name: 'L\'orso ruggisce', image: '/sentences/orso_ruggisce.svg', sound: '/sounds/orso_ruggisce.wav' },
    { id: 28, key: 'lupo_ulula', name: 'Il lupo ulula', image: '/sentences/lupo_ulula.svg', sound: '/sounds/lupo_ulula.wav' },
    { id: 29, key: 'volpe_stridisce', name: 'La volpe stridisce', image: '/sentences/volpe_stridisce.svg', sound: '/sounds/volpe_stridisce.wav' },
    { id: 30, key: 'lupo_aam', name: 'Il lupo fa aam', image: '/sentences/lupo_aam.svg', sound: '/sounds/lupo_aam.wav' },
    { id: 31, key: 'serpente_sibila', name: 'Il serpente sibila', image: '/sentences/serpente_sibila.svg', sound: '/sounds/serpente_sibila.wav' },
    { id: 32, key: 'coccodrillo_ringhia', name: 'Il coccodrillo ringhia', image: '/sentences/coccodrillo_ringhia.svg', sound: '/sounds/coccodrillo_ringhia.wav' },
    { id: 33, key: 'delfino_salta', name: 'Il delfino salta', image: '/sentences/delfino_salta.svg', sound: '/sounds/delfino_salta.wav' },
    { id: 34, key: 'balena_canta', name: 'La balena canta', image: '/sentences/balena_canta.svg', sound: '/sounds/balena_canta.wav' },
    { id: 35, key: 'ape_ronza', name: 'L\'ape ronza', image: '/sentences/ape_ronza.svg', sound: '/sounds/ape_ronza.wav' },
    { id: 36, key: 'grillo_cricchiola', name: 'Il grillo cricchiola', image: '/sentences/grillo_cricchiola.svg', sound: '/sounds/grillo_cricchiola.wav' },
    { id: 37, key: 'zanzara_ronza', name: 'La zanzara ronza', image: '/sentences/zanzara_ronza.svg', sound: '/sounds/zanzara_ronza.wav' },
    { id: 38, key: 'gabbiano_grida', name: 'Il gabbiano grida', image: '/sentences/gabbiano_grida.svg', sound: '/sounds/gabbiano_grida.wav' },
    { id: 39, key: 'aquila_strida', name: 'L\'aquila strida', image: '/sentences/aquila_strida.svg', sound: '/sounds/aquila_strida.wav' },
    { id: 40, key: 'falco_strida', name: 'Il falco strida', image: '/sentences/falco_strida.svg', sound: '/sounds/falco_strida.wav' },
    { id: 41, key: 'tigre_ruggisce', name: 'La tigre ruggisce', image: '/sentences/tigre_ruggisce.svg', sound: '/sounds/tigre_ruggisce.wav' },
    { id: 42, key: 'pinguino_strombazza', name: 'Il pinguino strombazza', image: '/sentences/pinguino_strombazza.svg', sound: '/sounds/pinguino_strombazza.wav' },
    { id: 43, key: 'koala_urla', name: 'Il koala urla', image: '/sentences/koala_urla.svg', sound: '/sounds/koala_urla.wav' },
    { id: 44, key: 'canguro_salta', name: 'Il canguro salta', image: '/sentences/canguro_salta.svg', sound: '/sounds/canguro_salta.wav' },
    { id: 45, key: 'zebra_nitrisce', name: 'La zebra nitrisce', image: '/sentences/zebra_nitrisce.svg', sound: '/sounds/zebra_nitrisce.wav' },
    { id: 46, key: 'giraffa_muggisce', name: 'La giraffa muggisce', image: '/sentences/giraffa_muggisce.svg', sound: '/sounds/giraffa_muggisce.wav' },
    { id: 47, key: 'ippopotamo_ringhia', name: 'L\'ippopotamo ringhia', image: '/sentences/ippopotamo_ringhia.svg', sound: '/sounds/ippopotamo_ringhia.wav' },
    { id: 48, key: 'tigre_ringhia', name: 'La tigre ringhia', image: '/sentences/tigre_ringhia.svg', sound: '/sounds/tigre_ringhia.wav' },
    { id: 49, key: 'leopardo_ringhia', name: 'Il leopardo ringhia', image: '/sentences/leopardo_ringhia.svg', sound: '/sounds/leopardo_ringhia.wav' },
    { id: 50, key: 'coyote_ulula', name: 'Il coyote ulula', image: '/sentences/coyote_ulula.svg', sound: '/sounds/coyote_ulula.wav' },
    { id: 51, key: 'iena_risa', name: 'La iena ride', image: '/sentences/iena_risa.svg', sound: '/sounds/iena_risa.wav' },
    { id: 52, key: 'gorilla_urla', name: 'Il gorilla urla', image: '/sentences/gorilla_urla.svg', sound: '/sounds/gorilla_urla.wav' },
    { id: 53, key: 'asino_ia', name: 'L\'asino fa ia', image: '/sentences/asino_ia.svg', sound: '/sounds/asino_ia.wav' },
    { id: 54, key: 'capra_bela', name: 'La capra bela', image: '/sentences/capra_bela.svg', sound: '/sounds/capra_bela.wav' },
    { id: 55, key: 'foca_abbaia', name: 'La foca abbaia', image: '/sentences/foca_abbaia.svg', sound: '/sounds/foca_abbaia.wav' },
    { id: 56, key: 'leopardo_ruggisce', name: 'Il leopardo ruggisce', image: '/sentences/leopardo_ruggisce.svg', sound: '/sounds/leopardo_ruggisce.wav' },
    { id: 57, key: 'gepardo_urla', name: 'Il ghepardo urlò', image: '/sentences/gepardo_urla.svg', sound: '/sounds/gepardo_urla.wav' },
    { id: 58, key: 'panda_grugnisce', name: 'Il panda grugnisce', image: '/sentences/panda_grugnisce.svg', sound: '/sounds/panda_grugnisce.wav' },
    { id: 59, key: 'cervo_bramisce', name: 'Il cervo bramisce', image: '/sentences/cervo_bramisce.svg', sound: '/sounds/cervo_bramisce.wav' },
    { id: 60, key: 'coccodrillo_sibila', name: 'Il coccodrillo sibila', image: '/sentences/coccodrillo_sibila.svg', sound: '/sounds/coccodrillo_sibila.wav' },
];

export function getRandomSentence(currentId) {
    const availableSentences = sentences.filter(s => s.id !== currentId);
    return availableSentences[Math.floor(Math.random() * availableSentences.length)];
}
